Added USBD_CDC_DataRxAsync, support of alt IF and control end of tx
SiliconLabs/uC-USBD pull request #12
Opened 2024-04-18 22:21 UTC by joetde

# Summary of change

* Added `USBD_CDC_DataRxAsync` which didn't exist before for async receive
* Added CDC notification codes from CDC 1.2 specification
* Added configuration to add alternate IF for data transfer (controlled by `USBD_CDC_SetAltIFEn`)
* Added configuration to be able to let the application control end of transfers (when to send ZLP)
* Default behaviour unchanged (`AltIFEn` set to false and `EndOfTx` set to true)

# Validation

Tested on MacOS, iPadOS, Linux and Android for CDC-ECM (implemented locally). OSs can enumerate the device, send and receive notification and data to it.

2024-09-04 03:08 UTC, wes-fflores requested changes

2024-09-04 03:08 UTC, wes-fflores commented on Class/CDC/usbd_cdc.c
> +                alt_if_nbr = USBD_IF_AltAdd(dev_nbr,
Align function arguments as:
```
                alt_if_nbr = USBD_IF_AltAdd(        dev_nbr,
                                                    cfg_nbr,
                                                    if_nbr,
                                            (void *)p_comm,
                                            (void *)0u,
                                                    p_err);
```
You could add "Alternate CDC Data Interface" as the alternative setting name instead of passing `(void *)0u`

2024-09-04 03:08 UTC, wes-fflores commented on Class/CDC/usbd_cdc.c
> +        USBD_BulkRxAsync(p_comm->DevNbr,
Align function arguments as:
```
        USBD_BulkRxAsync(p_comm->DevNbr,
                         p_data_ep->DataOut,
                         p_buf,
                         buf_len,
                         async_fnct,
                         p_async_arg,
                         p_err);
```

2024-09-04 03:08 UTC, wes-fflores commented on Class/CDC/usbd_cdc.c
> +*                                           USBD_CDC_SetEndOfTx()
Was there a particular scenario for adding this functionality?

2024-09-12 18:05 UTC, joetde commented on Class/CDC/usbd_cdc.c
> +*                                           USBD_CDC_SetEndOfTx()
Yes. A use case that we are looking into is to bridge two ECM interfaces, so when forwarding packets we would relied on the source interface to send the ZLP.
E.g. if the source has 1514 bytes to send over 512 byte transfers, it would send 512 bytes in one transfer, 512 in a second, and finally 490 (finalizing the overall transfer). But we wouldn't want to send ZLP for the first two 512 byte transfers. Hope this clarifies.

2024-09-14 01:54 UTC, wes-fflores approved these changes

2024-09-14 01:55 UTC, merged